apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: java-func-accelerator
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: java-func-accelerator
spec:
  params:
    - name: run-image
      value: your-registry.io/library/java-func-accelerator
  source:
    git:
      url: https://github.com
      ref:
        branch: main