SOURCE_IMAGE = os.getenv("SOURCE_IMAGE", default='your-registry.io/library/java-func-accelerator')

load('ext://pack', 'pack')

pack(SOURCE_IMAGE + ':latest',
    path='./java/',
    deps=['./java/bin/main'],
    live_update = [
        sync('./java/bin/main', '/workspace/BOOT-INF/classes'),
    ],
)

k8s_yaml(['kubernetes/deployment.yaml', 'kubernetes/service.yaml'])
k8s_resource('stock-value', port_forwards=8080)
allow_k8s_contexts('arn:aws:eks:us-east-2:083459807443:cluster/tap')