apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: java-func-accelerator
spec:
  template:
    spec:
      containers:
        - image: java-func-accelerator
          env:
            - name: RAPIDAPI_HOST
              valueFrom:
                secretKeyRef:
                  name: rapidapi-key-host
                  key: rapidapi.host
            - name: RAPIDAPI_KEY
              valueFrom:
                secretKeyRef:
                  name: rapidapi-key-host
                  key: rapidapi.key
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness